export const FETCH_USER = "FETCH_USER";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const FETCH_CLIENTS_ERROR = "FETCH_CLIENTS_ERROR";
export const FETCH_CLIENT_DETAILS = "FETCH_CLIENT_DETAILS";
export const FETCH_CLIENT_ERROR = "FETCH_CLIENT_ERROR";
export const FETCH_QUICKBOOKS_DATA = "FETCH_QUICKBOOKS_DATA";
export const FETCH_QUICKBOOKS_FAILED = "FETCH_QUICKBOOKS_FAILED";
